//AUTOGENERATED FILE FROM png2asset
// Conversion args: tiles.png -spr8x8 -tiles_only -o tiles.c

#ifndef METASPRITE_tiles_H
#define METASPRITE_tiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tiles_TILE_ORIGIN 0
#define tiles_TILE_W 8
#define tiles_TILE_H 8
#define tiles_WIDTH 32
#define tiles_HEIGHT 8
#define tiles_TILE_COUNT 4
#define tiles_PALETTE_COUNT 1
#define tiles_COLORS_PER_PALETTE 4
#define tiles_TOTAL_COLORS 4

BANKREF_EXTERN(tiles)

extern const palette_color_t tiles_palettes[4];
extern const uint8_t tiles_tiles[64];

#endif
